### ISSUE TITLE
Anchor links within the header section is draggable

### ISSUE THREAD

**Issue by Ammaryus** [WebAhead7/flags#18]
suggested solution : add draggable attribute to the anchor elements 
like this: <a href="index.html" draggable="false">Game</a>

**Comment by Ammaryus** [comment]
anther solution by javaScript is to prevent dragstart event  
/**
 * header hyper link drag display the link value ....
 */

 const headerLinks = document.querySelectorAll('header a');
 headerLinks.forEach(link =>{
     link.addEventListener('dragstart',(e)=>{
         e.preventDefault();
     })
 })

**Comment by Lujain-AbdUllatif** [comment]
Thanks for the note, new thing to learn.
