### ISSUE TITLE
using the this keyword...

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/flags#22]
https://github.com/WebAhead7/flags/blob/main/src/js/flag.js#L29-L42

this feels like someone saw an old React tutorial and thought this is a good idea 😄. (while if you check the new React that everyone is hyped about it has no `this` and no classes 🎉  ).

this is just a confusing syntax, it's not really needed, you could just make the function return a normal object, which has the method `play` and `stop` and a `sound` key. and it would **exactly** the same

```javascript
function sound(src) {
    const sound = document.createElement("audio");
    sound.src = src;
    sound.setAttribute("preload", "auto");
    sound.setAttribute("controls", "none");
    sound.style.display = "none";
    document.body.appendChild(sound);

    return {
        sound: sound,
        play: function () {
            sound.play();
        },
        stop: function () {
            sound.pause();
        }
    }
}
```

**Comment by nuwrss** [comment]
done :D
