### ISSUE TITLE
messy variable definitions

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/flags#24]
https://github.com/WebAhead7/flags/blob/main/src/js/flag.js#L46-L71

define all the variables that you need at the top of the file, also for these lines

https://github.com/WebAhead7/flags/blob/main/src/js/flag.js#L49
https://github.com/WebAhead7/flags/blob/main/src/js/flag.js#L54
https://github.com/WebAhead7/flags/blob/main/src/js/flag.js#L58

you could just start with display none in the css instead of settings the display none in javascript

**Comment by mjmajadly** [comment]
Thanks for the advice. Will take it into consideration in the future :)
